dist: xenial
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

services:
  - docker

cache:
  - pip

install:
  - pip install -r requirements.txt
  - pip install pylint pycodestyle coverage codecov # requirements only for CI
  - docker build -t selfhostingtools/services-monitoring:latest -f docker/Dockerfile .

script:
  - pylint --rcfile=.pylintrc monitoring.py docker/entrypoint.py tools notification probes tests
  - pycodestyle monitoring.py docker/entrypoint.py tools notification probes tests
  - python -m unittest discover tests -v
  - docker run --rm -it --entrypoint python selfhostingtools/services-monitoring:latest -m unittest discover tests -v
  - coverage run -m unittest discover
  - codecov

after_success:
  - echo $DOCKER_PASS | docker login -u selfhostingtools --password-stdin
  - docker push selfhostingtools/services-monitoring:latest
